[[main]]
  name       = 'Series'
  identifier = 'series'
  pageRef    = '/series'
  weight     = 1

  [[main]]
    name       = 'The Chosen One(s)'
    identifier = 'series.tco'
    pageRef    = '/series/the-chosen-one'
    parent     = 'series'
    Post       = "Harry Potter X Star Wars"

  [[main]]
    name       = 'Triumvirate'
    identifier = 'series.tri'
    pageRef    = '/series/triumvirate'
    parent     = 'series'
    Post       = "Harry Potter X Percy Jackson"

  [[main]]
    name       = 'Risa abr du skulblaka'
    identifier = 'series.risa'
    pageRef    = '/series/risa-abr-du-skulblaka'
    parent     = 'series'
    Post       = 'Harry Potter X Inheritance Cycle'

  [[main]]
    name       = 'Disillusioned Hearts'
    identifier = 'series.dh'
    pageRef    = '/series/disillusioned-hearts'
    parent     = 'series'
    Post       = 'Harry Potter'

[[more]]
  name       = 'Resources'
  identifier = 'resources'
  pageRef    = '/'
  weight     = 3

[[more]]
  name       = 'About'
  identifier = 'about'
  pageRef    = '/'
  weight     = 5

  [[more]]
  name       = 'Sustainability'
  identifier = 'sustainability'
  pageRef    = '/'
  parent     = 'about'
  weight     = 1

  [[more]]
  name       = 'Author'
  identifier = 'author'
  pageRef    = '/author'
  parent     = 'about'
  weight     = 2

[[author-name]]
  name       = '@user-name'
  identifier = 'bluesky'
  pageRef    = '/'
  weight     = 1
  pre        = 'bluesky'

[[author-name]]
  identifier = 'discord'
  pageRef    = '/'
  weight     = 2
  pre        = 'discord'

[[author-name]]
  name       = ''
  identifier = 'mastodon'
  pageRef    = '/'
  weight     = 3
  pre        = 'mastodon'

[[more]]
  name       = 'More Menu'
  identifier = 'more.menu'
  pageRef    = '/'
  weight     = 99

  [[more]]
    name       = 'That'
    identifier = 'more.menu.that'
    parent     = 'more.menu'
    pageRef    = '/'

    [[more]]
      name       = 'Never'
      identifier = 'more.menu.that.never'
      parent     = 'more.menu.that'
      pageRef    = '/'

      [[more]]
        name       = 'Too'
        identifier = 'more.menu.that.never.too'
        parent     = 'more.menu.that.never'
        pageRef    = '/'

        [[more]]
          name       = 'Deep'
          identifier = 'more.menu.that.never.too.deep'
          parent     = 'more.menu.that.never.too'
          pageRef    = '/'


[[footer]]
  identifier = 'email'
  pageRef    = '/'
  weight     = 1
  name       = 'email'
  pre        = 'email'

[[footer]]
  identifier = 'linkedin'
  pageRef    = '/'
  weight     = 2
  name        = 'linkedin'
  pre        = 'linkedin'

[[footer]]
  identifier = 'twitter'
  pageRef    = '/'
  weight     = 3
  name        = 'twitter'
  pre        = 'twitter'

[[footer]]
    identifier = 'bluesky'
    pageRef = '/'
    weight = 4
    name = 'bluesky'
    pre = 'bluesky'